stages:
  prepare:
    cmd: python src/prepare_data.py
    deps:
      - src/prepare_data.py
    outs:
      - data/iris.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/iris.csv
    outs:
      - model.pkl
      - metrics.json
